notifications:
  hipchat:
    rooms:
      secure: Pz5CQX/NtKLkk8c6kjhxipMS6kdQTj5jaeN9LC2k1IzERsqCYnx/nD2EV0cG4YJO0W3sMK3vaVgL5lLE3xHpe7wsLB/LWmxLY8QV0NJaSGOqqXAC4S5Yo7MRFd2S5fPWN7MC05SPpqiDveEle1fK6Gz7oHXSZxAFMyYnLRcaX3M=
language: php
php:
- '5.4'
- '5.5'
services:
- mysql
install:
- composer install --no-interaction
before_script:
- ./bin/tests install
script:
- ./bin/tests run --no-install
